### ISSUE TITLE
add folder title based on the topic

### ISSUE THREAD

**Issue by maharun0** [mhasan502/CSE225#2]
> **Current situation of folder titles:**
```
Lab 01
Lab 02
```

> **Suggested situation of folder titles:**
```
Lab 01 - Dynamic Memory Allocation
Lab 02 - Classes & Objects
.
.
.
Lab 13 - Binary Search Tree
Lab 14 - Priority Queue
Lab 15 - Graph 
```

**Comment by mhasan502** [comment]
Thanks for your concern. I will try to fix it this weekend Insha allah. Alternatively, you can edit the repo and submit a pull request.

**Comment by maharun0** [comment]
Ok, I will submit a pull request then..

**Comment by maharun0** [comment]
Update: I've submitted a pull request based on the changes in 43d55f8c5ada36c02d6182c76380837f77781047 commit, please review it and let me if there's any problem

**Comment by mhasan502** [comment]
Thanks for your contribution. Pull request accepted
